site_name: Questgiver Nøff
site_url: https://questgiver.iktim.no
site_description: En samling av oppdrag for læring, utforskning og utvikling.

repo_name: questgiver.iktim.no
repo_url: https://github.com/VaagenIM/questgiver
docs_dir: ../docs
site_dir: ../site
edit_uri: edit/main/

theme:
  name: material
  language: nb
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
  features:
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - content.code.annotate
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.prune
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  - attr_list
  - admonition
  - mdx_breakless_lists
  - meta
  - nl2br
  - smarty
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


plugins:
  - search
  - callouts
  - mkdocs-video
